// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:super_green_app/data/kv/models/app_data.dart';
import 'package:super_green_app/data/kv/models/device_data.dart';
import 'package:super_green_app/data/kv/models/user_settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppDataAdapter());
    registerAdapter(DeviceDataAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppDataAdapter());
    registerAdapter(DeviceDataAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}
